name: release docker image

on:
  release:
    types:
      - created


jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: sharepointoscar
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and Publish Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            sharepointoscar/skiapp:${{ github.event.release.tag_name }}
